#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-WNDR4300

on:
  schedule:
    - cron: 0 20 * * *
  push:
    branches:
      - master
env:
  SSH_ACTIONS: true
  TZ: Asia/Shanghai

jobs:

  build_openwrt_wndr4300:

    name: Build OpenWrt_wndr4300 and release
    runs-on: ubuntu-18.04

    steps:
      - name: Install compile software
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
          
      - name: Get Openwrt_wndr4300 source & compile
        run: |
          cd ~/work
          mkdir wndr4300
          cd wndr4300
          wget https://downloads.openwrt.org/releases/19.07.7/targets/ar71xx/nand/openwrt-imagebuilder-19.07.7-ar71xx-nand.Linux-x86_64.tar.xz
          xz -d openwrt-imagebuilder-19.07.7-ar71xx-nand.Linux-x86_64.tar.xz
          tar -xvf openwrt-imagebuilder-19.07.7-ar71xx-nand.Linux-x86_64.tar
          cd openwrt-imagebuilder-19.07.7-ar71xx-nand.Linux-x86_64/target/linux/ar71xx/image/
          sed -i -e 's/23552k/121856k/' ./Makefile
          sed -i -e 's/25600k/123904k/' ./Makefile
          cd ../../../..
          sudo make image PROFILE=WNDR4300V1
          
      - name: SSH connection to Actions
        uses:  P3TERX/ssh2actions@main
        if: env.SSH_ACTIONS == 'true'
              
      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/ar71xx/nand

      - name: Create release
        if: github.event == 'push'
        id: create_release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false      

      - name: Upload release asset
        if: github.event == 'push'
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/targets/*/*/
